#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
LA_TAG_PER = 1
LA_TAG_LOC = 2
LA_TAG_ORG = 3
LA_TAG_SFT = 4
LA_TAG_GME = 5
LA_TAG_SNG = 6
LA_TAG_NVL = 7
LA_TAG_VDO = 8
LA_TAG_STE = 9
LA_TAG_BRD = 10
LA_TAG_CTN = 11
LA_TAG_MDL = 12
LA_TAG_PDT = 13
LA_ERR_ENC = 1
LA_ERR_QTL = 2
